- src/main/java/com/bongsco/poscosalarybackend/test.txt
> ➕ Add: test code

- src/main/java/com/bongsco/poscosalarybackend/adjust/domain/AdjInfo.java
- src/main/java/com/bongsco/poscosalarybackend/adjust/domain/AdjSubject.java
- src/main/java/com/bongsco/poscosalarybackend/adjust/domain/DetailWorkStep.java
- src/main/java/com/bongsco/poscosalarybackend/adjust/domain/GradeAdjInfo.java
- src/main/java/com/bongsco/poscosalarybackend/adjust/domain/PaybandCriteria.java
- src/main/java/com/bongsco/poscosalarybackend/adjust/domain/PaymentAdjInfo.java
- src/main/java/com/bongsco/poscosalarybackend/adjust/domain/PaymentCriteria.java
- src/main/java/com/bongsco/poscosalarybackend/adjust/domain/QuarterlyProfit.java
- src/main/java/com/bongsco/poscosalarybackend/adjust/domain/RankIncrementRate.java
- src/main/java/com/bongsco/poscosalarybackend/adjust/domain/Salary.java
- src/main/java/com/bongsco/poscosalarybackend/adjust/domain/StationAdjInfo.java
- src/main/java/com/bongsco/poscosalarybackend/adjust/domain/Step.java
- src/main/java/com/bongsco/poscosalarybackend/baseup/domain/BaseupCriteria.java
- src/main/java/com/bongsco/poscosalarybackend/promoted/domain/PromotedAdditionalMoney.java
- src/main/java/com/bongsco/poscosalarybackend/user/domain/Department.java
- src/main/java/com/bongsco/poscosalarybackend/user/domain/Employee.java
- src/main/java/com/bongsco/poscosalarybackend/user/domain/Grade.java
- src/main/java/com/bongsco/poscosalarybackend/user/domain/Rank.java
- src/main/java/com/bongsco/poscosalarybackend/user/domain/Station.java
> 🐛 Baseentity added

- .github/workflow/deploy.yml
- Dockerfile
- src/main/java/com/bongsco/poscosalarybackend/adjust/controller/MainAdjController.java
- src/main/java/com/bongsco/poscosalarybackend/adjust/controller/PreprocessController.java
- src/main/java/com/bongsco/poscosalarybackend/adjust/domain/GradeAdjInfo.java
- src/main/java/com/bongsco/poscosalarybackend/adjust/domain/PaymentAdjInfo.java
- src/main/java/com/bongsco/poscosalarybackend/adjust/domain/RankIncrementRate.java
- src/main/java/com/bongsco/poscosalarybackend/adjust/domain/Salary.java
- src/main/java/com/bongsco/poscosalarybackend/adjust/domain/StationAdjInfo.java
- src/main/java/com/bongsco/poscosalarybackend/adjust/dto/AdjSubjectSalaryDto.java
- src/main/java/com/bongsco/poscosalarybackend/adjust/dto/MainAdjPaybandCriteriaResponse.java
- src/main/java/com/bongsco/poscosalarybackend/adjust/dto/request/ChangedEmployeeRequest.java
- src/main/java/com/bongsco/poscosalarybackend/adjust/dto/request/ChangedHighPerformGroupEmployeeRequest.java
- src/main/java/com/bongsco/poscosalarybackend/adjust/dto/request/ChangedSubjectListRequest.java
- src/main/java/com/bongsco/poscosalarybackend/adjust/dto/request/ChangedSubjectRequest.java
- src/main/java/com/bongsco/poscosalarybackend/adjust/dto/request/ChangedSubjectUseEmployeeRequest.java
- src/main/java/com/bongsco/poscosalarybackend/adjust/dto/response/CompensationEmployeeResponse.java
- src/main/java/com/bongsco/poscosalarybackend/adjust/dto/response/MainAdjPaybandBothSubjectsResponse.java
- src/main/java/com/bongsco/poscosalarybackend/adjust/dto/response/MainAdjPaybandCriteriaResponse.java
- src/main/java/com/bongsco/poscosalarybackend/adjust/dto/response/MainAdjPaybandSubjectsResponse.java
- src/main/java/com/bongsco/poscosalarybackend/adjust/repository/AdjSubjectRepository.java
- src/main/java/com/bongsco/poscosalarybackend/adjust/repository/PaybandCriteriaRepository.java
- src/main/java/com/bongsco/poscosalarybackend/adjust/repository/RankIncrementRateRepository.java
- src/main/java/com/bongsco/poscosalarybackend/adjust/service/AdjSubjectService.java
- src/main/java/com/bongsco/poscosalarybackend/adjust/service/PaybandCriteriaService.java
- src/main/java/com/bongsco/poscosalarybackend/global/dto/JsonResult.java
- src/main/java/com/bongsco/poscosalarybackend/user/repository/EmployeeRepository.java
- src/main/java/com/bongsco/poscosalarybackend/user/repository/SalaryRepository.java
> [BNG-46] 사전작업, 본조정 API 구현

- .github/workflows/deploy-dev.yml
- buildspec.yml
- github actions workflow 코드
- buildspec.yml 파일
- Resolved: #19
> [BNG-47] CodeBuild를 이용한 CI Pipeline 완성

- src/main/java/com/bongsco/poscosalarybackend/adjust/domain/AdjInfo.java
- src/main/java/com/bongsco/poscosalarybackend/adjust/domain/AdjInfoStep.java
- src/main/java/com/bongsco/poscosalarybackend/adjust/domain/AdjSubject.java
- src/main/java/com/bongsco/poscosalarybackend/adjust/domain/Step.java
- src/main/java/com/bongsco/poscosalarybackend/global/domain/AdjType.java
- src/main/java/com/bongsco/poscosalarybackend/global/domain/StepName.java
> [BNG-145] 바뀐 ERD 반영

- src/main/java/com/bongsco/poscosalarybackend/adjust/controller/CriteriaController.java
- src/main/java/com/bongsco/poscosalarybackend/adjust/domain/GradeAdjInfo.java
- src/main/java/com/bongsco/poscosalarybackend/adjust/domain/PaymentAdjInfo.java
- src/main/java/com/bongsco/poscosalarybackend/adjust/dto/request/SubjectCriteriaRequest.java
- src/main/java/com/bongsco/poscosalarybackend/adjust/dto/response/SubjectCriteriaResponse.java
- src/main/java/com/bongsco/poscosalarybackend/adjust/repository/GradeAdjInfoRepository.java
- src/main/java/com/bongsco/poscosalarybackend/adjust/repository/PaymentAdjInfoRepository.java
- src/main/java/com/bongsco/poscosalarybackend/adjust/service/AdjSubjectService.java
- src/main/java/com/bongsco/poscosalarybackend/adjust/service/CriteriaService.java
- src/main/java/com/bongsco/poscosalarybackend/global/exception/ErrorCode.java
- sql 처리가 매끄러운지 봐야 할 것 같습니다,
- Resolved: #33
> [BNG-152] 대상자 기준 설정 페이지 API 수정

- src/main/java/com/bongsco/poscosalarybackend/adjust/controller/CriteriaController.java
- src/main/java/com/bongsco/poscosalarybackend/adjust/dto/response/PaybandCriteriaConfigListResponse.java
- src/main/java/com/bongsco/poscosalarybackend/adjust/service/CriteriaService.java
> [BNG-154] payband 설정 페이지 get api

- src/main/java/com/bongsco/poscosalarybackend/adjust/controller/CriteriaController.java
- src/main/java/com/bongsco/poscosalarybackend/adjust/dto/request/PaybandCriteriaModifyRequest.java
- src/main/java/com/bongsco/poscosalarybackend/adjust/service/CriteriaService.java
> [BNG-159] payband 설정 patch api

- src/main/java/com/bongsco/poscosalarybackend/adjust/controller/PreprocessController.java
- src/main/java/com/bongsco/poscosalarybackend/adjust/dto/request/EmployeeSearchCondition.java
- 상진님이 초안에 잘 작성해주셔서 크게 수정할 부분이 없었습니다. 
- 프론트 단에서 request body의 형태로 가공할 예정입니다.
- Resolved: #39
> [BNG-156] 대상자 편성 페이지 API 수정

- src/main/java/com/bongsco/api/adjust/common/entity/AdjustEmploymentType.java
- src/main/java/com/bongsco/api/adjust/common/entity/AdjustGrade.java
> [BNG-172] Add column isActive

- src/main/java/com/bongsco/api/adjust/annual/controller/CriteriaController.java
- src/main/java/com/bongsco/api/adjust/annual/dto/PaymentRateDto.java
- src/main/java/com/bongsco/api/adjust/annual/dto/request/PaymentRateUpdateRequest.java
- src/main/java/com/bongsco/api/adjust/annual/dto/response/PaymentRateResponse.java
- src/main/java/com/bongsco/api/adjust/annual/dto/response/PaymentRateUpdateResponse.java
- src/main/java/com/bongsco/api/adjust/annual/repository/SalaryIncrementRateByRankRepository.java
- src/main/java/com/bongsco/api/adjust/annual/service/CriteriaService.java
- src/main/java/com/bongsco/api/adjust/common/repository/AdjustGradeRepository.java
- src/main/java/com/bongsco/api/employee/repository/GradeRepository.java
- src/main/java/com/bongsco/api/employee/repository/RankRepository.java
- src/main/resources/application.yml
> [BNG-153] 보상지급률 페이지 API

- src/main/java/com/bongsco/api/common/config/WebConfig.java
> [BNG-178] WebConfig 작성

- src/main/java/com/bongsco/api/adjust/annual/controller/CriteriaController.java
- src/main/java/com/bongsco/api/adjust/annual/controller/MainAdjustController.java
> [BNG-187] 경로 수정

- src/main/java/com/bongsco/api/common/config/WebConfig.java
> [BNG-188] CORS 설정해주기

- src/main/java/com/bongsco/api/adjust/common/dto/response/AdjustResponse.java
> ♻️ refactor null check for stepName in AdjustItemDto

- src/main/java/com/bongsco/api/adjust/baseup/entity/BaseupCriteria.java
- src/main/java/com/bongsco/api/adjust/common/entity/AdjustStep.java
- src/main/java/com/bongsco/api/adjust/common/entity/RepresentativeSalary.java
- src/main/java/com/bongsco/api/adjust/common/entity/Step.java
- src/main/java/com/bongsco/api/adjust/promoted/entity/PromotedAdditionalMoney.java
- src/main/java/com/bongsco/api/employee/entity/Department.java
- src/main/java/com/bongsco/api/employee/entity/Employee.java
- src/main/java/com/bongsco/api/employee/entity/EmploymentType.java
- src/main/java/com/bongsco/api/employee/entity/Grade.java
- src/main/java/com/bongsco/api/employee/entity/Rank.java
`@SQLRestriction("deleted = false")
`
이 부분을 모든 테이블에 추가했습니다.
- Resolved: #81
> [BNG-190] SQLRestriction 모든 entity에 추가

- src/main/java/com/bongsco/api/adjust/annual/service/AdjustService.java
- src/main/java/com/bongsco/api/adjust/common/dto/response/AdjustResponse.java
- src/main/java/com/bongsco/api/adjust/common/repository/AdjustRepository.java
- src/main/java/com/bongsco/api/adjust/common/repository/reflection/AdjustItemProjection.java
> ✨ feature add step url in main page

- src/main/java/com/bongsco/api/common/config/WebConfig.java
> 🔧 Allow HTTP Cloudfront origins

- src/main/java/com/bongsco/api/adjust/common/repository/AdjustRepository.java
> ✨ add deleted condition in native query

- src/main/java/com/bongsco/api/adjust/annual/controller/CriteriaController.java
- src/main/java/com/bongsco/api/adjust/annual/service/CriteriaService.java
- 기존에 param으로 받던 선정된 직급 리스트를 adjust_grade에 isactive를 활용하는 로직으로 변경했습니다.
- 
- 
- Resolved: #이슈번호
- 
-
> [BNG-192] 보상지급률 페이지 API 수정

- src/main/java/com/bongsco/api/adjust/common/repository/AdjustSubjectRepository.java
> 🐛 Fix merge error

- src/main/java/com/bongsco/api/adjust/common/entity/AdjustEmploymentType.java
- src/main/java/com/bongsco/api/adjust/common/entity/AdjustGrade.java
> [BNG-199] Change Builder.Default : false -> true

- src/main/java/com/bongsco/api/adjust/annual/controller/MainAdjustController.java
- src/main/java/com/bongsco/api/adjust/annual/service/AdjustSubjectService.java
- src/main/java/com/bongsco/api/adjust/common/repository/AdjustSubjectRepository.java
- 필터가 직급이랑 평가등급 여러개 눌렀을때 다 뜨는지
- Resolved: #98
> [BNG-195] 필터 로직 변경

- src/main/java/com/bongsco/api/common/utils/ExcelDownloadController.java
- src/main/java/com/bongsco/api/common/utils/ExcelDownloadService.java
> [BNG-197] Swagger docs & add headers

- src/main/java/com/bongsco/api/adjust/annual/service/AdjustService.java
> [BNG-193] 메인 페이지 POST API 수정

- src/main/java/com/bongsco/api/adjust/annual/controller/MainAdjustController.java
- src/main/java/com/bongsco/api/adjust/annual/service/AdjustSubjectService.java
- src/main/java/com/bongsco/api/adjust/common/repository/AdjustSubjectRepository.java
> [BNG-204] 필터 로직 변경 2

- src/main/java/com/bongsco/api/adjust/annual/controller/CriteriaController.java
- src/main/java/com/bongsco/api/adjust/annual/controller/PreparationController.java
- src/main/java/com/bongsco/api/adjust/annual/service/AdjustSubjectService.java
- src/main/java/com/bongsco/api/adjust/common/repository/AdjustStepRepository.java
- src/main/java/com/bongsco/api/adjust/common/service/AdjustStepService.java
> [BNG-206] 페이밴드 적용여부 초기화

- src/main/java/com/bongsco/api/adjust/annual/service/CriteriaService.java
- src/main/java/com/bongsco/api/adjust/common/entity/AdjustSubject.java
- src/main/java/com/bongsco/api/adjust/common/repository/AdjustStepRepository.java
- src/main/java/com/bongsco/api/adjust/common/repository/AdjustSubjectRepository.java
> [BNG-207] AdjustCriteria soft delete is fixed

- web/src/main/java/com/bongsco/web/adjust/common/repository/AdjustRepository.java
> 연봉조정페이지 SQL Query code 수정

- web/src/main/java/com/bongsco/web/adjust/annual/controller/MainChartController.java
- web/src/main/java/com/bongsco/web/adjust/annual/dto/response/EmploymentTypeDistributionResponse.java
- web/src/main/java/com/bongsco/web/adjust/annual/dto/response/GradeDistributionResponse.java
- web/src/main/java/com/bongsco/web/adjust/annual/dto/response/HeadCountTrendResponse.java
- web/src/main/java/com/bongsco/web/adjust/annual/dto/response/SalaryByGradeTrendResponse.java
- web/src/main/java/com/bongsco/web/adjust/annual/dto/response/SalaryRangeResponse.java
- web/src/main/java/com/bongsco/web/adjust/annual/dto/response/TenureDistributionResponse.java
- web/src/main/java/com/bongsco/web/adjust/annual/dto/response/TotalSalaryTrendResponse.java
- web/src/main/java/com/bongsco/web/adjust/common/repository/AdjustRepository.java
- web/src/main/java/com/bongsco/web/adjust/common/repository/AdjustSubjectRepository.java
> [BNG-223] Main 페이지 차트 API

- web/src/main/java/com/bongsco/web/adjust/annual/service/AdjustSubjectService.java
- web/src/main/java/com/bongsco/web/adjust/common/repository/AdjustSubjectRepository.java
- web/src/main/java/com/bongsco/web/adjust/common/repository/reflection/EmployeeAndSalaryProjection.java
> [BNG-222] 결과 페이지 로직 이상 고침 

- web/src/main/java/com/bongsco/web/adjust/annual/service/CriteriaService.java
> [BNG-228] Fix adjust build

- web/src/main/java/com/bongsco/web/adjust/annual/service/AdjustSubjectService.java
- web/src/main/java/com/bongsco/web/adjust/common/repository/AdjustSubjectRepository.java
> [BNG-237] 결과페이지 에러 고침

- web/src/main/java/com/bongsco/web/adjust/common/repository/AdjustRepository.java
> Backend Query 수정

- web/src/main/java/com/bongsco/web/adjust/annual/service/AdjustSubjectService.java
> [BNG-238] 산식오류

- web/src/main/java/com/bongsco/web/adjust/common/repository/AdjustSubjectRepository.java
> Chart Repository 수정

- web/src/main/java/com/bongsco/web/adjust/annual/service/AdjustSubjectService.java
- web/src/main/java/com/bongsco/web/adjust/common/repository/AdjustRepository.java
- web/src/main/java/com/bongsco/web/adjust/common/repository/AdjustSubjectRepository.java
> [BNG-242] 결과페이지 500 에러

- web/src/main/java/com/bongsco/web/adjust/annual/controller/MainAdjustController.java
- web/src/main/java/com/bongsco/web/adjust/annual/entity/PaybandCriteria.java
- web/src/main/java/com/bongsco/web/adjust/annual/repository/reflection/MainResultProjection.java
- web/src/main/java/com/bongsco/web/adjust/annual/service/AdjustService.java
- web/src/main/java/com/bongsco/web/adjust/annual/service/AdjustSubjectService.java
- web/src/main/java/com/bongsco/web/adjust/annual/service/CriteriaService.java
- web/src/main/java/com/bongsco/web/adjust/common/repository/AdjustSubjectRepository.java
- web/src/main/java/com/bongsco/web/adjust/common/repository/reflection/EmployeeAndSalaryProjection.java
> [BNG-240] payband 초기화 이슈
